import { IColorsApi } from "@li/src/styles/interfaces/colors";

export const colorsBase: IColorsApi = {
    general: "black",
    primary: "black",
    onPrimary: "black",
    primaryContainer: "black",
    onPrimaryContainer: "black",
    inversePrimary: "black",
    secondary: "black",
    onSecondary: "black",
    secondaryContainer: "black",
    onSecondaryContainer: "black",
    tertiary: "black",
    onTertiary: "black",
    tertiaryContainer: "black",
    onTertiaryContainer: "black",
    background: "black",
    onBackground: "black",
    surface: "black",
    onSurface: "black",
    surfaceVariant: "black",
    onSurfaceVariant: "black",
    surfaceTint: "black",
    inverseSurface: "black",
    inverseOnSurface: "black",
    error: "black",
    onError: "black",
    errorContainer: "black",
    onErrorContainer: "black",
    outline: "black",
    outlineVariant: "black",
    scrim: "black",
    surfaceBright: "black",
    surfaceContainer: "black",
    surfaceContainerHigh: "black",
    surfaceContainerHighest: "black",
    surfaceContainerLow: "black",
    surfaceContainerLowest: "black",
    surfaceDim: "black",
}

export type ColorKey = keyof IColorsApi